### ISSUE TITLE
Hey! 👋

### ISSUE THREAD

**Issue by caoxiemeihao** [ggdream/scss#3]
老师你好！请问一下 [vite-plugin-electron](https://www.npmjs.com/package/vite-plugin-electron) 这 npm 包可不可以转交给我来开发呢，我想把它做成一个可用的版本！🥺

**Comment by ggdream** [comment]
你好，当然可以。应该怎么转给你呢

**Comment by caoxiemeihao** [comment]
谢谢老师！😄
npm 官方有操作方式的
https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

<img width="611" alt="image" src="https://user-images.githubusercontent.com/26263658/161245382-67ec489e-a06c-48e0-b9a7-335588b4db7e.png">
<img width="605" alt="image" src="https://user-images.githubusercontent.com/26263658/161245459-740892e2-f385-4256-8a3c-4a28774144e1.png">

**Comment by caoxiemeihao** [comment]
您这边可以直接删掉，然后我重新注册
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/26263658/161361947-7e338e03-5515-405d-acf1-4a6bd68408eb.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/26263658/161361937-225012f2-1da9-478e-b51e-c2a33245a5b6.png">

**Comment by ggdream** [comment]
已经删掉了(๑•̀ㅂ•́)و✧

**Comment by caoxiemeihao** [comment]
貌似我还是发不上去 😅
要么麻烦您再操作下不，把我加下管理员
<img width="902" alt="image" src="https://user-images.githubusercontent.com/26263658/161375058-683e8e01-c5e1-4c8d-9d18-60ad686742e8.png">

---

这是我的 npm https://www.npmjs.com/~caoxiemeihao

<img width="820" alt="image" src="https://user-images.githubusercontent.com/26263658/161375094-915cca9a-4716-41ce-8156-85c48c73d36c.png">
